apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      version: v1.0
      init:
        command: [argocd-vault-plugin]
        args: ["generate", "./"]
      generate:
        command: [sh, -c]
        args: ["find . -name '*.yaml' -o -name '*.yml' | xargs -I {} argocd-vault-plugin generate {}"]
      discover:
        find:
          command: [sh, -c]
          args: ["find . -name '*.yaml' -o -name '*.yml' | xargs grep -l '<path:' || true"]

---