creation_rules:
  - path_regex: secrets/db-secrets.yaml
    hc_vault_transit_uri: "http://10.0.0.58:8200/v1/sops/keys/"
    hc_vault_transit_key_name: "firstkey"
    hc_vault_addr: "http://10.0.0.58:8200"
    hc_vault_auth_method: "token"
    hc_vault_token_path: "./mariadb/vault-token.yml"
