apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 3
  serviceName: mariadb 
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
      - name: vault-agent
        image: hashicorp/vault:1.20
        env:
        - name: VAULT_ADDR
          value: "http://10.0.0.58:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        command:
        - sh
        - -c
        - |
          ROOT_PASSWORD_ENCRYPTED=$(cat /etc/encrypted-secrets/root-password)
          vault write -field=plaintext transit/decrypt/db ciphertext="$ROOT_PASSWORD_ENCRYPTED" > /shared/secrets/root-password
          
          WP_PASSWORD_ENCRYPTED=$(cat /etc/encrypted-secrets/wp-password)
          vault write -field=plaintext transit/decrypt/db ciphertext="$WP_PASSWORD_ENCRYPTED" > /shared/secrets/wp-password
          
        volumeMounts:
        - name: shared-secrets
          mountPath: /shared/secrets
        - name: encrypted-secrets-volume
          mountPath: /etc/encrypted-secrets
          readOnly: true
      containers:
      - name: mariadb
        image: mariadb:10.11
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: "/etc/secrets/root-password"
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD_FILE
          value: "/etc/secrets/wp-password"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: shared-secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: shared-secrets
        emptyDir: {}
      - name: encrypted-secrets-volume
        secret:
          secretName: mysql-secret
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 3Gi  

