apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  root-password: "vault:v1:3UNKvhrFnxl6HDYv1FzNpJUHS10OQVMXf/sdi7l3z7hpsAyp" 
  wp-password: "vault:v1:ToxyRWvMV1Ik7Mrb8RogtPaJUczOiZnic7WFKC7exRRYPQ==" 
         