apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: wp-secret-store
    kind: ClusterSecretStore
  target:
    name: wp-secret
    creationPolicy: Owner
  data:
  - secretKey: root-password
    remoteRef:
      key: wordpress
      property: wp-password