apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
  - deployment-wp.yaml
  - pvc-wordpress.yaml
  - loadbalancer.yaml
  - secrets.yaml

patchesStrategicMerge:
  - service-patch.yaml
