---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBkFrWHY1TZAweaJsbGUcoiT6GPN02+q8Sog52T5qgJnbNuT8PvmpAQuW4Jfmvy5b/SWm2SgkaTiA9YivnfWLiPHox488j1GRL1TkMfJJC737FE2aMJ9LmG30ZWO642NuEaYfeusjOS4+1BwtpYPYsIS1T6Y1gGNqOsXZSN5nPCy4GjWu6xXXygQu/7RatUa9L88XFQRI2J5+B3Kf0S+vBZvkzwCiB4/1WgwjV2GIj8iZCbCboSou6yMW/XlPGaw38OawfXtBMKPlQYJ99KegZkq7MXl6VU5HmDpsGsRK9sjDng/0kgCCEPWMV3zX/k657+GYGmQP0w9qNfbSIcZq3dBLVk8Kv3Gtd2WFjkZCe9noJlYzLLzThO70W0FKKJEE3UKLCkUFli6lKlhWoUwSaQpxUJ6K+yoBNmF4aHUIwlxdfWKg1bhJPIOmXIeB5450wcAdff00uYlak4ZIJz5gH60OQL/AP+dvYcBNuZUnZDqcVsz7HUbrAqCx5sAZicDqQDAZM3gwhtYjX/jjuIB6Rc8m17MUEwFfu2jwsSNhAbwWqDSoXy6fC3OQjxRe1xA4aBWGuM7wEuYu4XJShuai5QvZ6hp4nbocegRARzfFtb9RguKM6dN/LciOr0zL7rH8GkNQ6xR/u/LPFx1tCZP472Q2bD/KTR2S1oqSZIolMnX9rl8i8I8CuUnMsNk+6b9UQQtFxOLeffhvkbpw==
    admin-user: AgBnYpRKCUI6IIPbc5XqOpZ+MAdBfRf1POzQB1sWx1MukqR84s0IkHl4ziUhe95MJkIDcim97wpHF1H0s6k9MA9PbAgWFR5pWHg9qjTU99srUJ4H7YZzvOtvoYrpPDSaKcFvj7MlNzJhczflXoAk7ZsCxzuPtK0hDiMKR7N1gG3h36KUok5JVdweLhv0qeYP9MQAcD70gjrp3pXiZna5i2e0vHXXRYaqJe9jPJnw9VO9pBEsQwgxehRYOMON8ryykqaxp6/Ila+VoIOcfVgLnvZccGno3bmbnrBuCgcAMIcvSXQU6VbVHC8ilAut2MRqHy9IUVNvEyTNd961iYMjwobu6cMaFCzFL1a65Ivk545HXg0HBlv0VbKLuzlQLRFWHKToLPBlN5A0OJOE+xR25i0rOMnYCGmu7I6cfh3JoK+CoSuzXBuALcOabKpkWzSqOiV4QPQ0Cr5pR+xc+czt0WvR24qnubn6WtbfSz4SQFlPuiUrp0RQhDjFIwzZfpRf0JeAFNjVw670/llGBEFwbGuo7hqQ5oKWo6xUtJrCBHA1PrlOnO++AbZc9ZHHGsUVVJBX9V+KEi63olLrQCVoZwbN6YMzf4osY18mND71Y1yn07t4pMLsDszW9YJRbMICjcJyoDDUPNWmbd1gvUiIAQnoKrczUT1xRV5glBlFqIf+7Cx9VOn8BIUbkRHvHPldoNXOYckpFg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
