apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
spec:
  pxc:
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: rook-ceph-block 
        accessModes:  
        - ReadWriteOnce
        resources:
          requests:
            storage: 6Gi