apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 86.2.3        
      helm:
        valueFiles:
          - $values/kube-prometheus/kube-prometheus-stack-values.yaml

    - repoURL: https://github.com/NahlaAbdAlghany/DevOps-projects.git
      targetRevision: kube-promethues
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
