apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 9.1.4
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: ["master", "data", "ingest"]
      cluster.initial_master_nodes: ["quickstart-es-default-0","quickstart-es-default-1","quickstart-es-default-2"]
      node.store.allow_mmap: false