apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        namespace: bookinfo-app
        appName: bookinfo-app
        path: bookinfo-app/
  template:
    metadata:
      name: "bookinfo-app"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/NahlaAbdAlghany/DevOps-Mentorship-Tasks.git'
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true