apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        env: test
        namespace: elastic-system
        appName: elasticsearch-operator
        path: eck-operator/base
        syncWave: "1"
  template:
    metadata:
      name: "{{.appName}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.syncWave}}"
      finalizers:
      - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      source:
        repoURL: 'https://github.com/NahlaAbdAlghany/DevOps-Mentorship-Tasks.git'
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated: 
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - pruneLast=true
        # - AllowCRDDeletion=true
        # - ApplyOutOfSyncOnly=false
  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: name
          operator: In
          values:
          - test
    deletionOrder: reverse
  syncPolicy:
    applicationsSync: create-update