apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: ElasticSearch-operator
        url: https://kubernetes.default.svc
        namespace: elasticsearch-operator
        appName: ElasticSearch-operator
        path: ElasticSearch-cluster/overlay
  template:
    metadata:
      name: "elasticsearch-operator"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/NahlaAbdAlghany/DevOps-Mentorship-Tasks.git'
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true