apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: ElasticSearch-cluster
        url: https://kubernetes.default.svc
        namespace:  monitoring
        appName: grafana-operator
        path: grafana-operator/overlays/namespace_scoped
  template:
    metadata:
      name: "grafana-operator"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/NahlaAbdAlghany/DevOps-Mentorship-Tasks.git'
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true