apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  description: Project for cluster-scoped applications
  
  # Allow cluster-scoped resources
  clusterResourceWhitelist:
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'admissionregistration.k8s.io'
    kind: ValidatingWebhookConfiguration
  - group: ''
    kind: Namespace
  
  # Allow all namespaced resources
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
    
  destinations:
  - namespace: '*'
    server: '*'
    
  sourceRepos:
  - '*'