apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NahlaAbdAlghany/DevOps-Mentorship-Tasks.git'
    path: "Task 3/wordpress"
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-v1.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true