apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: productpage-ztunnel
  namespace: bookinfo-app
spec:
  selector:
    matchLabels:
      app: productpage
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/bookinfo-app/sa/bookinfo-gateway-istio
        - cluster.local/ns/bookinfo-app/sa/waypoint
        # - cluster.local/ns/bar/sa/waypoint  -- this not needed as waypoint proxy in bar namespace is not calling productpage``
        # - cluster.local/ns/bar/sa/curl -- this not needed as curl in bar namespace is not calling productpage, we need to label the namespace with ambient anyway