apiVersion: ENC[AES256_GCM,data:E1E=,iv:/+Js51UNaZCkUEwu5Yt6ovEEGlKT4gGeaDsRMVYV0t8=,tag:qHtekrUB0lfUVhjB3Zv9ag==,type:str]
kind: ENC[AES256_GCM,data:dp5wbztg,iv:jE7uDD5JUIpMb5v6tDeKvJfJey69Os3nnXv+vB4P0zo=,tag:1B0Os3y4Q4rEfgZIZGZ44A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uCTQXHxJ1YjwTPpN85svWYZGJ7rmdvASFI0=,iv:EsvJIQKLAiS1+N3va4FA5r0+tos7kYdJIgbj/pKznIo=,tag:NmiNabFWHD5Ze78qtp1yTA==,type:str]
    namespace: ENC[AES256_GCM,data:e/gTS9kNlFtujzI=,iv:zvwOF/NdWgpKkEnemSMsaz5IV5781ZhF+w4Gk8/2esI=,tag:BpR0N9GmRCrRTSmhlCuPAA==,type:str]
type: ENC[AES256_GCM,data:09Oehvzl,iv:VQyonua8SFGyqfgBZ0BoqFGQuUKruMjizWViwewtUGA=,tag:9fhaLXN5O8KtYU+7Nh6G4Q==,type:str]
data:
    elastic: ENC[AES256_GCM,data:CsQUt8aD38glBSxZYjL4ovoqMGUWZpMG,iv:uH71pP8abiGDkXMEK7nJuQcSvzRP2tvp+QEigwBv+BE=,tag:7tQyHu2CIE6BALPjJUK7Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://10.0.0.58:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2025-10-16T11:13:05Z"
          enc: vault:v1:rbunMzHjlUJUDygwJ/yao1inkb4RbmjrV5ftF1RDgFTn9rqRiLlaCYMfl4WlluAaEx7A1SmKj2dz/XVf
    age: []
    lastmodified: "2025-10-16T11:13:05Z"
    mac: ENC[AES256_GCM,data:cokl2SP98J61xxAryWeCFIsonSRpDVzhTdeNGDKK/qsPXo9KHTL1fTAI4139d7FPiFeozEnBDEutjcHqbZ0h8kO3jlq8yS3txh+dQoQOG8m7rjhxdDmHnCb6EP1nTdiaQvvIL3FASnn2RC9k0UiU3V5DnbID97iu8NBWJRFr9c8=,iv:7tg0fZ9TxoK3M6BXC9xtiUhGpguixQqe3O1Ih1ixSik=,tag:ai3LaTnmABr0+/oUiTc8Ag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
