apiVersion: ENC[AES256_GCM,data:4Zo=,iv:wOycve2XQ0nMec6Okl14D51KM/rL077rIKoO0DQdv1A=,tag:UAhN877nm55nAPILPZdS6Q==,type:str]
data:
    elastic: ENC[AES256_GCM,data:iMyeifZHUGCcaQljMRdFmoc2MOOEHiKRprHyO12Qjfw=,iv:VdzlM+lkXYSJqgUoXLFDHCfHtzGikB7loFWH17xcwII=,tag:ONQ+Ap1Ow3u4A8vk47Jtgg==,type:str]
kind: ENC[AES256_GCM,data:XUNZF+j0,iv:vD9w+9NlaZi+2e0937Exe7+RoVPwEzK/4T+FoN330oc=,tag:R9RRr8e/HAW1KGSb0bVP5g==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:BTJLmNxayR4RpjpZzBWW7Org7l8=,iv:UJdo9hRCTuHcDq6YZZd9m4Uy1+S+e6F5ZPFA9XVHwOs=,tag:2BxPnLTPzy5bNhO9CICebQ==,type:str]
    labels:
        common.k8s.elastic.co/type: ENC[AES256_GCM,data:/3HqmmnhgJ0nRkNQ+w==,iv:UBB7IHkW+R+zB9qNVzaOjqYdMy2tV6kZ6ICwVDpkmKk=,tag:5Dg8B63Q8W56RHAQuBe/oA==,type:str]
        eck.k8s.elastic.co/credentials: ENC[AES256_GCM,data:AWOgHQ==,iv:tWjFlzgxyGNt00KI2/5/qfPrzH0BATplBbG78HYveJk=,tag:SyfFoT6Am0MNHnGQLVDFnA==,type:str]
        eck.k8s.elastic.co/owner-kind: ENC[AES256_GCM,data:wQkE+slhOeJh5q8Hag==,iv:jl4I26Tuv0yGg3CsiFEjMSMWplU6zbDhaHoGmT8KyAY=,tag:gbs/98noF1bYnFfx2trrqA==,type:str]
        eck.k8s.elastic.co/owner-name: ENC[AES256_GCM,data:lvbEY+StDPvhCA==,iv:+mtJWqJrndpPoI5NWyoV8mWs0G8zEowtV7pxyw2ZXls=,tag:fb/Q7Fwijuy46zrN2tLh7Q==,type:str]
        eck.k8s.elastic.co/owner-namespace: ENC[AES256_GCM,data:qjh5FFVTJgzYVkE=,iv:/Y8uxp06M2omjVQGClK+7xTronWXNXJkadxiWlxF6u0=,tag:gvDDReeNHM6hjBls6z7Abw==,type:str]
        elasticsearch.k8s.elastic.co/cluster-name: ENC[AES256_GCM,data:kaJixNj+OBDvIw==,iv:BZkracwIsIP4j3RRwNWbq/6X0+3g4MYF/9MwqT8HR+s=,tag:QqDf6HFA3EBU7bIrxizmdg==,type:str]
    name: ENC[AES256_GCM,data:8C2dCKi5q+oHbatOXxYPIjPJRCFZAeArCyE=,iv:txyx8yk+bw6hA445g7fHXSyYxpFtjKYf9+85tXmSQAc=,tag:q+o7YJjOoDzG7z7BwGkTcQ==,type:str]
    namespace: ENC[AES256_GCM,data:Orkz6hwAYgIw+YE=,iv:V8rmWTgN6G3XjHlB8tR4r03hv8aHbV8w/guuqj/v1AE=,tag:0eKEYefkG98rT7Os4fJFBA==,type:str]
    resourceVersion: ENC[AES256_GCM,data:DM1Dv+qsQtY=,iv:WywXSd76WLOF+ZwyS1RXfTBa02y6Dby/aFjSdpmXcfA=,tag:LhZ7FEjf30rLyvdMFIMRDQ==,type:str]
    uid: ENC[AES256_GCM,data:19Qg7elMmXprNdZuDG6O/PFJxflMm6zsEG/jP7VcmNiIaCYv,iv:HI5akFznV7g5l2cFmH8h2O9CpoHgax9dB0y/qum4V38=,tag:2bK9TS0rjNXF2NwLvcf36Q==,type:str]
type: ENC[AES256_GCM,data:/X47iT7D,iv:0027WjPjG4UT1udkBmK+o3+d7qHZoRGW7A/2PEHbI2s=,tag:xRudCqVKw6AenJFMvpzFIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://10.0.0.58:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2025-10-16T15:44:18Z"
          enc: vault:v1:7cAuJCMsd3F1Z9O+h9DPEMF9VHqntskRjA8Rdekv1zWfW0OFsLrujZPW6nQSJwoacTp6tZ7LQwW0tdxb
    age: []
    lastmodified: "2025-10-16T15:44:18Z"
    mac: ENC[AES256_GCM,data:YGJeLfG0bFD0gpBCQxpZpOa7rZU13OJbAc8qJhUmjzilxq69D6PDhLmqq2qIN0hZT1GUV9vbpqmbdmQHJMtTdGC0jAykyhTxsBk42DpuVn2Oqlj26Z2Aj4zQpQ4lpL/ri3fBQZT8YohQ4ZBNujsHVYSUexM3LJBbl894KMD7e8E=,iv:wL4YJ9CkGI0+yom8HDIULn3Z3PGb2RbDlGRnJhCPZBA=,tag:kfuyODqKhjI3Bp8LlDkCEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
