apiVersion: ENC[AES256_GCM,data:vk0=,iv:1jRSBcny+icSWuSfIWGb3J39pKr6sQrlAoqV+Extdoo=,tag:qjqCcPABsUW/HDgow4/pzQ==,type:str]
kind: ENC[AES256_GCM,data:2/+NdpqM,iv:b1CMbU9vN7ctpfi4/HAKxzjpeIeB64jb0yrCf/nBPRw=,tag:xO5GGhbZfiluPpmo5RQnQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ssf/Fgt5f4GmgmAYfWqJBld5Js4fY2kd2ZQ=,iv:+Pm+sS/SnuHQ80FvhoqFXy8U+mIfdvEADWPsgg7vF/Y=,tag:XEBEEbx4fn+8i9QzukpzsA==,type:str]
    namespace: ENC[AES256_GCM,data:Xr8a2wRZRk57Zo0=,iv:BS/nIyyJoKa2hOek4ERIC6LL9Qa12kGtXqkeQKCZLCI=,tag:/f4fheV4ExjeA4XprCsjbA==,type:str]
type: ENC[AES256_GCM,data:hltks8L/,iv:a08EK60teWdtNLlbeLqpck3yUipbjV95I7qVl/qkTxE=,tag:qHmuWeV/MY5Oebgv8yOzkA==,type:str]
data:
    password: ENC[AES256_GCM,data:8E80caBszvye2P1P22dvHGhKhZt5yOPG,iv:VhgFDaU3fEPaoeP5LayR0hCUP1oSmlROpNzTg7G83zs=,tag:wvze2nfQMU5gWKkqc7zLPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://10.0.0.58:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2025-10-13T21:02:29Z"
          enc: vault:v1:M5xFJD41XTeyaohrdPHbbv7kB3kSo9ycr+b6EUm3QfbGpftvc1sqtxW9g4akiO8fzjveGHZ5DTnFyOwn
    age: []
    lastmodified: "2025-10-13T21:02:29Z"
    mac: ENC[AES256_GCM,data:2jiA2iK8w1+aI4x5HrYWPPt59TCOzEWJS1K/shO8lr/OtetLl9ktTagDNVo3Gt60JhYXiwkgB8nnvJgUqgi0akqFooW/+i3QTfI+1xl9038sQVvg9eheXJsf9ARcbT7mwqZxjHYDsozCiFFrw6q8i0Tw/WJjG71c4svTE5AUnz4=,iv:6ytpkGKQTvnn6/hCC2xcGothZ5DfzVjKzgw96G8kMEM=,tag:DyULgxUIUpg84Y7WRLBKXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
