apiVersion: ENC[AES256_GCM,data:zdM=,iv:sp8NSBo77ctOlq2ICch5iv5IP+iMvegP7mBH4kk037A=,tag:tHRFrXDpkd72LmkMkBfLbw==,type:str]
data:
    password: ENC[AES256_GCM,data:3n3Anb282hx5fZHyrpJceU8w7FeIWx5XA8tQDV0+tHc=,iv:Z/IaPkZCspwSo9AUYrS6Ox32PgeT3aVaG0M8C0xASfc=,tag:Nye4kw9lrYmDWi5s3G73iA==,type:str]
    username: ENC[AES256_GCM,data:gidJa6O3OXVintyxcfVHzw==,iv:idkDctJfBxpahMvOWU4s5qgXdDlmagMMh9+koFdc5sw=,tag:eAyqYIOtTXPuuV5qjzobEw==,type:str]
kind: ENC[AES256_GCM,data:3X4eoeyv,iv:qPRZI0nHSCbf5NDS+iZe55ZG4O2DdXxus+i26G4g1WY=,tag:F5WnY4LV1KRDKcumfLeu5g==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:ZLdOfHIAQQe15Ed7MLikzDdr,iv:/7K6+sArdybnYpanT8+yeKMin8h+opCByafQ8I3fGhw=,tag:kezHcUMjXWYRuWbznIW1rQ==,type:str]
    namespace: ENC[AES256_GCM,data:KkuzXo4=,iv:W9B3NIREb9bjJKOEgiYUSE9Kg6GjCxGMz+qdxtbrK+Y=,tag:S/n8g+83RH7N3937L2bktg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:686893581621:key/395f669e-1b8b-47e8-bd5d-da75c44f4f37
          created_at: "2026-08-24T18:48:23Z"
          enc: AQICAHjjjAEwLiL/u99M+9xB430/dhNid5WcLyqwrtddiDsCLwF28mhyF48lw5d2EHVoz9fvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9QNqb9NQvyKm0nQ/AgEQgDvhA7Sguyaqs4fkWoa8i1KwI5QMXJ5sC1eYNI0j8tsYdP7pIvZcWGYtpaqDMwH64Fkb8Vja71j2ifssCw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-24T18:48:24Z"
    mac: ENC[AES256_GCM,data:FQNoga13TyjwHZ2rJY8aJKDYCe+ymgC6f6lzoBl3UNfm3uKK1DqtcFrYR+jXOC4KrO6WfVsR5ZMrGgLt5jgjx+UWHwDRzglYQtgyuIITSuzVKYK+pRz0hMF+0LUm+yzArn2rxE+70NuT3avZ2M3LowL0No4eTiYO5VnMzJ7ab0A=,iv:MQsbI0bqh/ImPGuxumOTvCW62/LnAX25CGy4DZses68=,tag:cB9kI5F6MD7hszKg/JVe9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
