apiVersion: ENC[AES256_GCM,data:/5M=,iv:6JGJkJ6q2OKJK7DMKU/Gcma5y205YZ83zwVOxGRm6VE=,tag:fsMMVrRAPcoB9IhOFam84g==,type:str]
data:
    password: ENC[AES256_GCM,data:dW7dPfv5tg34VEhJaL2fwYU/FgkS0iktQk4NoG/mkSg=,iv:C14DLmQsBfuqhFaLWRTbTiJmSvUNz7H8Sbvlla/nPtQ=,tag:xo98dvmKJlRNW35SWxnItA==,type:str]
    username: ENC[AES256_GCM,data:OqeUr1Kqk5fRVdnujG2W+w==,iv:VraSZzaaWXVSrRevNq6wGZ99XK2wUf3SF/uSrChgAU4=,tag:HSBWCXi/z6BM4zFqHwfYYw==,type:str]
kind: ENC[AES256_GCM,data:y4hShnYg,iv:wjjkVTwswWhGtZLDN2yQTu4F149+g7jjus+5ZKg0a4s=,tag:cNYehVvrfwVlW9t/m4RVaQ==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:ubHyzccjx++HulTXkRCd8io4,iv:nsyWXeNoBYKXxUdqlCPSSeeANk4wMHIxG7LJZ3OuQbE=,tag:hI26LP6ENpWo+/I5vP/oNg==,type:str]
    namespace: ENC[AES256_GCM,data:KWpMTlA=,iv:B7sfjW1JR08B4rMIUoOWRS6Ftb4L3pkr153Di421hD0=,tag:vmN59ie+rc5LYN6Wu4z7Wg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:686893581621:key/0426af15-4642-4467-8911-804d68f921e7
          created_at: "2026-08-22T18:20:24Z"
          enc: AQICAHh6IQnobzY5D19847YpDIlD7zw2Q43l2NtdqFkBqHRyPAFo/IdtmKXKoQ00+BhQW0RTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5BI4Neikd/CsMRYaAgEQgDvtBaQS58NwEV9fCK+FyV8t2usZt9OSLahwb7m02x+rQkBTxjT7NkD+86OadtILnLz5hk5MszC1IYQjbA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-22T18:20:25Z"
    mac: ENC[AES256_GCM,data:I7+e6YZBn+7tf0kT5xj3jdQPRb3KNpcr+0clRFrwqtuupPW6Jzh/KO3Sf8SetZp+ZFBCynEPcES5UCG4TOsDfxTUE25qZy9vgz5t5nfriFHgMb66CJ6r/3bcK34wvIC3eb3VaQILGLUNREekx+8qA18K2L3aPGjObvqdALXvE+Y=,iv:TTA9a1/G6UOg/JSPh4HUyNA77SJ0VGOu2mDRd/L/oTM=,tag:92ZJiBm14D9OTC8XHcvvsg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
