apiVersion: ENC[AES256_GCM,data:JBs=,iv:CidL/l+GnIiluUSWwXcJSQx/j/wczNqZ4Mbo6nbfdH8=,tag:iLimSPVYDWTm/x49z8juBg==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:6pXt5ucIjH20Hf6yuRsBByUSZYkAJzaaDekBAbw8huo=,iv:lRc7F/5AOeDEVIYyAzuZAoMHXTJzVE+VeQR0ByvKE/w=,tag:gwPgJpJsvUG1QcPfWwxmYQ==,type:str]
    admin-user: ENC[AES256_GCM,data:i6cZpoyX3tw=,iv:GRhLHLuyZb+9UzNYAcG0xYfI8MlIMf5ZXLfcEYlG4v8=,tag:3lxYVRFDs64XKix9Xk8pZw==,type:str]
kind: ENC[AES256_GCM,data:qLNYnvpM,iv:8pqO2Wb00VT/8vzHphDl60IZ7t4rV3UxlTnfutMW3wE=,tag:zwrM6chVO7h3tg4X3hfVbA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:NwnuDPPdvpZtPZSMYX/wzcgJShE=,iv:cpH34hoWTOREZ5KSUNLWj21wZqS7RQ3Tk976h7LrceM=,tag:ea/R3Raxmzi0vXziXx4q5A==,type:str]
    namespace: ENC[AES256_GCM,data:5TLvnG0VpiIzAg==,iv:MbgVxKEAoS0gzoWWaBYyP7+4NubdRYSDJOf890Kt8Ek=,tag:JhiQ6jr8iOw/FqRXHaNsiw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:686893581621:key/395f669e-1b8b-47e8-bd5d-da75c44f4f37
          created_at: "2026-08-24T18:48:24Z"
          enc: AQICAHjjjAEwLiL/u99M+9xB430/dhNid5WcLyqwrtddiDsCLwH6g2Ajl4kpBPxHzDOTLZwKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXRLnK/9yIpDmAkwwAgEQgDv3YtsOocXLst1UMkjOoXFl8rikutjiBo+73x/rX9MiZjjUI9axI2Y/e7Xj/NtyVloIxlZT6BYM8Ty3JQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-24T18:48:25Z"
    mac: ENC[AES256_GCM,data:QlcNp1qRKhurQ4VOmEblPdXiA0m0hn5YqaXbAjkZUoxmtQBN6oCJveVo/pCUt48/0cKBbKPngU6DCakvzTeNefdbznZBxI/ZW52GsYhh6jAKB98oEjmG7g9a/eLB9ib1K6FfuZ4CES82M+8sjsjIVT0452GGTkvyK38HapNJJCU=,iv:nbMpa8/7mrblIZVP1KPaqc3k6TPTEO3AIYww3CMbm+c=,tag:IrEeiY2Vn6LHFIaow4MXpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
