apiVersion: ENC[AES256_GCM,data:YBs=,iv:PNAn8oZqMWJVUmM79gIpRY3CBnA8fHMM3dYl/1twJTY=,tag:R8QaQBD51zw+jd9OjYUfPw==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:R3bObHfsZpwGXAt0WK64t2jmydLBntShwuClQpJ1Pss=,iv:ci6WcFWJDc7x/CUBDZOTvpCMsveF5WQfbhUAesQhGlA=,tag:0vBYuV6wSrCLZ0ZOvIe4cQ==,type:str]
    admin-user: ENC[AES256_GCM,data:TFqPqEutxTo=,iv:IoNFNR98zYvruZTdTwyfz2s3c9zAvA0Iy4MlN9e1pjo=,tag:xEghoq0Jk+r+2SunRg3wRA==,type:str]
kind: ENC[AES256_GCM,data:h2/dJ/B1,iv:0/hR9tljswXqozQzeLhavtOkyFtFMMTosJVAM3LOPO0=,tag:d1emGcPZWytCHoOU7oryRA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:ywh30Jrcc/6Tko1qSLchFsvULtw=,iv:312lD5yUi/MhlusroWvqM1bK48G5tJpZ5qGwuclqtS4=,tag:8PDuVv+xaTZXQ6edtPsZ/w==,type:str]
    namespace: ENC[AES256_GCM,data:h8Y3BThZebMjsw==,iv:YzubObICTUGSSoGVAgDsbYeIw2bhp41gc5njKd4eE0s=,tag:dYd1s0zYfHu+M3wQ6t6fKA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:686893581621:key/0426af15-4642-4467-8911-804d68f921e7
          created_at: "2026-08-22T18:30:27Z"
          enc: AQICAHh6IQnobzY5D19847YpDIlD7zw2Q43l2NtdqFkBqHRyPAFwbR/GqUXoNL368iEDzidFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQB6te6D7d1Ox7n0oAgEQgDu/3XdrgKK6kALbmFzPpRQtMR3W3grKn7/LB5daNl2ziWlHla/TuHPL8rpcXupJKaNKpd4SJRBVeJjzpw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-22T18:30:28Z"
    mac: ENC[AES256_GCM,data:rX8/zkzYshe9T/xne0yQX0vcHWlWpKnzBhYxatbG5onm9PD7e9voCQjMSsA5loi04gj8mpuUrsMZGXmi1fnCNXJUYt2LpoPXh94RY3w1DgcM1gvGtdb76w1VRc6A8r1Nuenw09873a002r67keb7piR8pA7fcNSidtDkKJ6CydE=,iv:gp4UPtl2zIxv458+Xx1jtHiwLYMCSZ5wcboeLUtdWq0=,tag:46Vxklc/LNkq82MN59NOiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
