apiVersion: ENC[AES256_GCM,data:E8g=,iv:Tc5Bj/pKsIFUk/1J59yb+IcCZ1vSsvEwNCAov7jluA0=,tag:xr56SwDj8VIiTBxY8OOEqg==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:gyEYl/371OUkuJr9T4/V1g==,iv:rUvKeGrrm85F/PC00/9yC5XmXrz5KzQ7IATEMQHRga0=,tag:1HMfb5ni/EXg7RC+Hyeraw==,type:str]
    admin-user: ENC[AES256_GCM,data:AQfX382vT84=,iv:epVBt9KOLB4lVbL+sOpGOn0DC+NJD67v8d2kzBRj/aE=,tag:LXYOexdcw2lKcupgC4+hxQ==,type:str]
kind: ENC[AES256_GCM,data:RmylseMi,iv:dW2uy/Wrkc9fBbQ/zjYxCLRTEqManlXVZqzQXDGEj+E=,tag:Uhr1ZofNl8wUVIHBpCptRQ==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:oI1oghMYN9jP9MCbNNIJIGSyg/Y=,iv:OKZZn+FvblDNgwSPPxX8AbqscgKA1mFm4t0zyokQCJk=,tag:GyHuRBSW8NuE9cXgqOyL5w==,type:str]
    namespace: ENC[AES256_GCM,data:mSypAtRTM5VwdA==,iv:jbd5nBZZMDS6xiiRNXRevyxY9Y6qomVdJmobXKZxfc8=,tag:BShYdZLOUgeCR8UV//fbQg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:852405188872:key/903b3c8f-b0af-4416-8cb8-83cc41c9f263
          created_at: "2026-07-03T01:09:05Z"
          enc: AQICAHhcXqPgM0cs/+XjZUZ2+YUa1vOy+ctB/J2qz286ogDQAwHUPMhbnrZjG9KVfcaO95QwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMRYuRma0nsCZTG89AgEQgDvB4l133+1hpH12jwXttrC3dqSg6by62LgV2Ah8vLADdMnxTwOGvSHBSjFtOST9QVyuqNGthoFApiq/RQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-03T01:09:06Z"
    mac: ENC[AES256_GCM,data:E8EmqCtXHUiJPbP3L+WytGGR7XEXUZF2Z6QwSSDZCGUOLelO9RPA+aG1lxKhqZwD6g67WBOZZJoHovIxkAhVk8PICzqFkZWe3eY+KwBT/aJ4mkM2bZ0d0bKVnm9C+GjhEkOB052RZ+STgsXK9BEBkXUolOxCMPxVLrbHhxCP+rQ=,iv:fIJwXHCqBac4KKpt0VVxCnuxaLtsyoTSubZfy/RO9YY=,tag:TntIPAaG+q5F7N+Fd3vbgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
