apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cluster-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./grafana-admin-secret.enc.yaml
  - ./gitea-admin-secret.enc.yaml
